apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: django-oci-v1
  labels:
    commit: ${WERCKER_GIT_COMMIT}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-oci
  template:
    metadata:
      labels:
        app: django-oci
        commit: ${WERCKER_GIT_COMMIT}
    spec:
      containers:
      - name: django-oci
        image: ${DOCKER_REPO}:${WERCKER_GIT_BRANCH}-${WERCKER_GIT_COMMIT}
        imagePullPolicy: Always
        ports:
        - name: django-oci
          containerPort: ${PORT}
          protocol: TCP
      imagePullSecrets:
        - name: wercker
---
apiVersion: v1
kind: Service
metadata:
  name: django-oci
  labels:
    app: django-oci
    commit: ${WERCKER_GIT_COMMIT}
spec:
  ports:
  - port: 30000
    targetPort: ${PORT}
  selector:
    app: django-oci
  type: ClusterIP
---
